version: "3.0"
services:
    laravel-web:
      depends_on:
        - laravel-db
      container_name: laravel-web
      image: bitnami/laravel:latest
      environment:
        - DB_HOST=laravel-db
        - DB_USERNAME=root
        - DB_DATABASE=test
        - DB_PASSWORD=123456
      ports:
        - "80:3000"
      networks:
        - laraveldev_net
      restart: always
      volumes:
        - E:/58160702/DBMS/581607022/labdbms/app:/app
        - E:/58160702/DBMS/581607022/labdbms/webdata:/root

    laravel-db:
      container_name: laravel-db
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=123456
      networks:
        - laraveldev_net
      restart: always
      volumes:
        - E:/58160702/DBMS/581607022/labdbms/mysql:/var/lib/mysql
        - E:/58160702/DBMS/581607022/labdbms/data:/root

    laravel-phpmyadmin:
      container_name: laravel-phpmyadmin
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOST=laravel-db
      ports:
        - "82:80"
      networks:
        - laraveldev_net
      restart: always

networks:
    laraveldev_net:
      driver: bridge

